/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientPeriodOrganization {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "max_allowed_memberships",
        skip_serializing_if = "Option::is_none"
    )]
    pub max_allowed_memberships: Option<i64>,
    #[serde(
        rename = "admin_delete_enabled",
        skip_serializing_if = "Option::is_none"
    )]
    pub admin_delete_enabled: Option<bool>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(
        rename = "logo_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub logo_url: Option<Option<String>>,
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    #[serde(rename = "has_image", skip_serializing_if = "Option::is_none")]
    pub has_image: Option<bool>,
    #[serde(rename = "members_count", skip_serializing_if = "Option::is_none")]
    pub members_count: Option<i64>,
    #[serde(
        rename = "pending_invitations_count",
        skip_serializing_if = "Option::is_none"
    )]
    pub pending_invitations_count: Option<i64>,
    #[serde(rename = "public_metadata", skip_serializing_if = "Option::is_none")]
    pub public_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Unix timestamp of creation.
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
    /// Unix timestamp of last update.
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<i64>,
}

impl ClientPeriodOrganization {
    pub fn new() -> ClientPeriodOrganization {
        ClientPeriodOrganization {
            id: None,
            object: None,
            name: None,
            max_allowed_memberships: None,
            admin_delete_enabled: None,
            slug: None,
            logo_url: None,
            image_url: None,
            has_image: None,
            members_count: None,
            pending_invitations_count: None,
            public_metadata: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "organization")]
    Organization,
}

impl Default for Object {
    fn default() -> Object {
        Self::Organization
    }
}
