/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientPeriodSignUp {
    /// String representing the object's type. Objects of the same type share the same value.
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<Object>,
    /// Unique identifier for this sign up.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// List of required fields which need to be supplied to the current sign-up. These fields are mandatory in order for the sign-up to satisfy the attached registration policy and be marked as complete.
    #[serde(rename = "required_fields", skip_serializing_if = "Option::is_none")]
    pub required_fields: Option<Vec<String>>,
    /// List of optional fields which can be supplied to the current sign-up. These fields are not required and their absence does not prevent the sign-up to be marked as complete.
    #[serde(rename = "optional_fields", skip_serializing_if = "Option::is_none")]
    pub optional_fields: Option<Vec<String>>,
    /// List of the missing fields which still need to be supplied to the current sign-up. These fields are mandatory in order for the sign-up to satisfy the attached registration policy and be marked as complete.
    #[serde(rename = "missing_fields", skip_serializing_if = "Option::is_none")]
    pub missing_fields: Option<Vec<String>>,
    /// List of fields which are already supplied to the current sign-up but they need to be verified. Example of such fields are email addresses and phone numbers.
    #[serde(rename = "unverified_fields", skip_serializing_if = "Option::is_none")]
    pub unverified_fields: Option<Vec<String>>,
    /// Group for all available verifications.
    #[serde(rename = "verifications", skip_serializing_if = "Option::is_none")]
    pub verifications: Option<Box<models::ClientPeriodSignUpPeriodVerifications>>,
    #[serde(
        rename = "username",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub username: Option<Option<String>>,
    #[serde(
        rename = "email_address",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub email_address: Option<Option<String>>,
    #[serde(
        rename = "phone_number",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub phone_number: Option<Option<String>>,
    #[serde(
        rename = "web3_wallet",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub web3_wallet: Option<Option<String>>,
    #[serde(
        rename = "password_enabled",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub password_enabled: Option<Option<bool>>,
    #[serde(
        rename = "first_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub first_name: Option<Option<String>>,
    #[serde(
        rename = "last_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub last_name: Option<Option<String>>,
    /// Custom JSON that callers can use to store arbitrary values that make sense in the context of the current sign up.
    #[serde(rename = "unsafe_metadata", skip_serializing_if = "Option::is_none")]
    pub unsafe_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Custom JSON that can be used to store arbitrary values which will end up in the user's public metadata. This field can only be populated from the application's BE. At this point, this can be done via invitations.
    #[serde(rename = "public_metadata", skip_serializing_if = "Option::is_none")]
    pub public_metadata: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(
        rename = "external_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_id: Option<Option<String>>,
    #[serde(
        rename = "created_session_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_session_id: Option<Option<String>>,
    #[serde(
        rename = "created_user_id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_user_id: Option<Option<String>>,
    #[serde(
        rename = "abandon_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub abandon_at: Option<Option<i64>>,
}

impl ClientPeriodSignUp {
    pub fn new() -> ClientPeriodSignUp {
        ClientPeriodSignUp {
            object: None,
            id: None,
            status: None,
            required_fields: None,
            optional_fields: None,
            missing_fields: None,
            unverified_fields: None,
            verifications: None,
            username: None,
            email_address: None,
            phone_number: None,
            web3_wallet: None,
            password_enabled: None,
            first_name: None,
            last_name: None,
            unsafe_metadata: None,
            public_metadata: None,
            external_id: None,
            created_session_id: None,
            created_user_id: None,
            abandon_at: None,
        }
    }
}
/// String representing the object's type. Objects of the same type share the same value.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "sign_up_attempt")]
    SignUpAttempt,
}

impl Default for Object {
    fn default() -> Object {
        Self::SignUpAttempt
    }
}
///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "abandoned")]
    Abandoned,
    #[serde(rename = "missing_requirements")]
    MissingRequirements,
    #[serde(rename = "complete")]
    Complete,
}

impl Default for Status {
    fn default() -> Status {
        Self::Abandoned
    }
}
