/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientPeriodEnvironment {
    #[serde(rename = "auth_config", skip_serializing_if = "Option::is_none")]
    pub auth_config: Option<Box<models::ClientPeriodAuthConfig>>,
    #[serde(rename = "display_config", skip_serializing_if = "Option::is_none")]
    pub display_config: Option<Box<models::ClientPeriodDisplayConfig>>,
    #[serde(rename = "user_settings", skip_serializing_if = "Option::is_none")]
    pub user_settings: Option<Box<models::ClientPeriodUserSettings>>,
    #[serde(
        rename = "organization_settings",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_settings: Option<Box<models::ClientPeriodOrganizationSettings>>,
    #[serde(rename = "maintenance_mode", skip_serializing_if = "Option::is_none")]
    pub maintenance_mode: Option<bool>,
}

impl ClientPeriodEnvironment {
    pub fn new() -> ClientPeriodEnvironment {
        ClientPeriodEnvironment {
            auth_config: None,
            display_config: None,
            user_settings: None,
            organization_settings: None,
            maintenance_mode: None,
        }
    }
}
