/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettingsPeriodAttributes {
    #[serde(rename = "email_address")]
    pub email_address: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "phone_number")]
    pub phone_number: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "username")]
    pub username: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "password")]
    pub password: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "first_name")]
    pub first_name: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "last_name")]
    pub last_name: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "ticket")]
    pub ticket: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "web3_wallet")]
    pub web3_wallet: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "authenticator_app")]
    pub authenticator_app: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "backup_code")]
    pub backup_code: Box<models::UserSettingsPeriodAttribute>,
    #[serde(rename = "passkey")]
    pub passkey: Box<models::UserSettingsPeriodAttribute>,
}

impl UserSettingsPeriodAttributes {
    pub fn new(
        email_address: models::UserSettingsPeriodAttribute,
        phone_number: models::UserSettingsPeriodAttribute,
        username: models::UserSettingsPeriodAttribute,
        password: models::UserSettingsPeriodAttribute,
        first_name: models::UserSettingsPeriodAttribute,
        last_name: models::UserSettingsPeriodAttribute,
        ticket: models::UserSettingsPeriodAttribute,
        web3_wallet: models::UserSettingsPeriodAttribute,
        authenticator_app: models::UserSettingsPeriodAttribute,
        backup_code: models::UserSettingsPeriodAttribute,
        passkey: models::UserSettingsPeriodAttribute,
    ) -> UserSettingsPeriodAttributes {
        UserSettingsPeriodAttributes {
            email_address: Box::new(email_address),
            phone_number: Box::new(phone_number),
            username: Box::new(username),
            password: Box::new(password),
            first_name: Box::new(first_name),
            last_name: Box::new(last_name),
            ticket: Box::new(ticket),
            web3_wallet: Box::new(web3_wallet),
            authenticator_app: Box::new(authenticator_app),
            backup_code: Box::new(backup_code),
            passkey: Box::new(passkey),
        }
    }
}
