/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettingsPeriodAttribute {
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(
        rename = "used_for_first_factor",
        skip_serializing_if = "Option::is_none"
    )]
    pub used_for_first_factor: Option<bool>,
    #[serde(rename = "first_factors", skip_serializing_if = "Option::is_none")]
    pub first_factors: Option<Vec<String>>,
    #[serde(
        rename = "used_for_second_factor",
        skip_serializing_if = "Option::is_none"
    )]
    pub used_for_second_factor: Option<bool>,
    #[serde(rename = "second_factors", skip_serializing_if = "Option::is_none")]
    pub second_factors: Option<Vec<String>>,
    #[serde(rename = "verifications", skip_serializing_if = "Option::is_none")]
    pub verifications: Option<Vec<String>>,
    #[serde(rename = "verify_at_sign_up", skip_serializing_if = "Option::is_none")]
    pub verify_at_sign_up: Option<bool>,
}

impl UserSettingsPeriodAttribute {
    pub fn new() -> UserSettingsPeriodAttribute {
        UserSettingsPeriodAttribute {
            enabled: None,
            required: None,
            used_for_first_factor: None,
            first_factors: None,
            used_for_second_factor: None,
            second_factors: None,
            verifications: None,
            verify_at_sign_up: None,
        }
    }
}
