/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserSettingsPeriodRestrictions {
    #[serde(rename = "allowlist")]
    pub allowlist: Box<models::UserSettingsPeriodRestrictionsPeriodAllowlist>,
    #[serde(rename = "blocklist")]
    pub blocklist: Box<models::UserSettingsPeriodRestrictionsPeriodBlocklist>,
    #[serde(rename = "block_email_subaddresses")]
    pub block_email_subaddresses: Box<models::UserSettingsRestrictionsBlockEmailSubaddresses>,
    #[serde(rename = "block_disposable_email_domains")]
    pub block_disposable_email_domains: Box<models::UserSettingsRestrictionsBlockEmailSubaddresses>,
    #[serde(rename = "ignore_dots_for_gmail_addresses")]
    pub ignore_dots_for_gmail_addresses:
        Box<models::UserSettingsRestrictionsBlockEmailSubaddresses>,
}

impl UserSettingsPeriodRestrictions {
    pub fn new(
        allowlist: models::UserSettingsPeriodRestrictionsPeriodAllowlist,
        blocklist: models::UserSettingsPeriodRestrictionsPeriodBlocklist,
        block_email_subaddresses: models::UserSettingsRestrictionsBlockEmailSubaddresses,
        block_disposable_email_domains: models::UserSettingsRestrictionsBlockEmailSubaddresses,
        ignore_dots_for_gmail_addresses: models::UserSettingsRestrictionsBlockEmailSubaddresses,
    ) -> UserSettingsPeriodRestrictions {
        UserSettingsPeriodRestrictions {
            allowlist: Box::new(allowlist),
            blocklist: Box::new(blocklist),
            block_email_subaddresses: Box::new(block_email_subaddresses),
            block_disposable_email_domains: Box::new(block_disposable_email_domains),
            ignore_dots_for_gmail_addresses: Box::new(ignore_dots_for_gmail_addresses),
        }
    }
}
